version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "widen"
    # Limit open pull requests to 1 to avoid multiple PRs for the same dependency.
    open-pull-requests-limit: 1
