version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "widen"
    # Limit open pull requests to 5
    open-pull-requests-limit: 5
