name: relic
description: A lightweight web server inspired by Shelf.
version: 0.2.0
repository: https://github.com/serverpod/relic

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  http: '>=1.0.0 <2.0.0'
  test: ^1.24.2
  test_descriptor: ^2.0.1
