name: Bug Report
description: Encountered unexpected behavior or exceptions in Relic? Report it here!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        When reporting a bug, please complete this template thoroughly to help us address the issue effectively!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the unexpected behavior you encountered.
    validations:
      required: true
      
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect?
      description: Explain the behavior you expected to occur.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce this?
      description: Provide detailed steps or a minimal reproducible example to reproduce the bug.
      
  - type: textarea
    id: steps-to-fix
    attributes:
      label: What steps should we take to fix this?
      description: If you have suggestions for fixing the bug, please describe them here.
      
  - type: textarea
    id: example-changes
    attributes:
      label: Do you have an example of where the bug occurs?
      description: Share a minimal reproducible example or reference code where the issue can be observed.

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, share relevant debug/error logs here in the code block below.
      render: shell

  - type: textarea
    attributes:
      label: Output of relevant commands
      value: |
        Provide the output of any relevant commands or tools (e.g., `dart --version`).

  - type: dropdown
    id: affected-platforms
    attributes:
      label: Affected platforms
      multiple: true
      options:
        - All
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: Share any additional context or information about the bug.

  - type: checkboxes
    id: terms
    attributes:
      label: Are you interested in working on a PR for this?
      options:
        - label: I want to work on this
